Repository Making-my-own-weapon/Coconut-Backend, pull requests merged in 2025-07, with the labels that each got.

#8 feat(#4): 로그인 API 구현
  .github/ISSUE_TEMPLATE/기능-개발.md
  .github/ISSUE_TEMPLATE/버그-픽스.md
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/create-user.dto.ts
  src/auth/dto/login-user.dto.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/guards/jwt-refresh.guard.ts
  src/auth/strategies/jwt-refresh.strategy.ts
  src/auth/strategies/jwt.strategy.ts
  src/main.ts
  src/users/entities/user.entity.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Feature

#10 fix(#9): problem 백엔드 api 로직 수정
  mysql-init/schema.sql
  src/problems/dtos/create-db-problem.dto.ts
  src/problems/dtos/problem-summary.dto.ts
  src/problems/entities/problem.entity.ts
  src/problems/problems.controller.ts
  src/problems/problems.service.ts
Labels: Bug

#12 fix(#11): schema의 json 배열 default 삭제
  mysql-init/schema.sql
  src/problems/entities/problem.entity.ts
Labels: Bug

#18 chore(#15): CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  ecs-task-definition.json
  src/app.module.ts
  src/health/health.controller.ts
Labels: Chore

#33 feat(#32): 회원탈퇴
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Feature

#52 refactor(#51): 음성채팅 로직 분리 및 개선
  src/app.module.ts
  src/editor/editor.gateway.ts
  src/voice/voice.gateway.ts
  src/voice/voice.module.ts
Labels: Refactor, fix

#85 feat(#84): 비밀번호 변경 구현
  src/users/dto/change-password.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature
